{
 "title": "ZooKeeper by Prometheus",
 "description": "ZooKeeper Dashboard for Prometheus metrics scraper",
 "tags": [ "v4" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info{job=\"$job\",application=\"$application\"}, instance)"
    }
   },
   { "name": "application", "label": "application", "query": "${VAR_APPLICATION}" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "znode_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} znode_count"
    },
    {
     "expr": "ephemerals_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} ephemerals"
    }
   ]
  },
  {
   "title": "znode_count_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(znode_count{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{`{{instance}}`}} znode_count_rate"
    },
    {
     "expr": "rate(ephemerals_count{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{`{{instance}}`}} ephemerals_rate"
    }
   ]
  },
  {
   "title": "global_sessions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "global_sessions{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "local_sessions ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "local_sessions{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "write_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "write_per_namespace_sum{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} write_per_namespace:{{`{{key}}`}}"
    }
   ]
  },
  {
   "title": "read_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "read_per_namespace_sum{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} read_per_namespace:{{`{{key}}`}}"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} approximate_data_size"
    }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packets_received{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} packets_received"
    }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packets_sent{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} packets_sent"
    }
   ]
  },
  {
   "title": "response_packet_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "response_packet_cache_misses{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} response_packet_cache_misses"
    },
    {
     "expr": "response_packet_cache_hits{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} response_packet_cache_hits"
    },
    {
     "expr": "response_packet_get_children_cache_misses{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} response_packet_get_children_cache_misses"
    },
    {
     "expr": "response_packet_get_children_cache_hits{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} response_packet_get_children_cache_hits"
    }
   ]
  },
  {
   "title": "unrecoverable_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unrecoverable_error_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} unrecoverable_error_count"
    }
   ]
  },
  {
   "title": "digest_mismatches_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "digest_mismatches_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} digest_mismatches_count"
    }
   ]
  },
  {
   "title": "startup_snap_load_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "startup_snap_load_time_sum{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} startup_snap_load_time"
    }
   ]
  },
  {
   "title": "startup_txns_loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "startup_txns_loaded_sum{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} startup_txns_loaded"
    }
   ]
  },
  {
   "title": "db_init_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dbinittime_sum{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} db_init_time"
    }
   ]
  },
  { "title": "Quorum/Leader Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "quorum_size",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(quorum_size{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "quorum_size"
    }
   ]
  },
  {
   "title": "leader",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "format": "ms",
   "valueName": "name",
   "targets": [
    {
     "expr": "leader_uptime{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "leader_uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "leader_uptime{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} leader_uptime"
    }
   ]
  },
  {
   "title": "learner/observer",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(learners{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "learners"
    },
    {
     "expr": "max(synced_non_voting_followers{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "synced_non_voting_followers"
    },
    {
     "expr": "max(synced_observers{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "synced_observers"
    }
   ]
  },
  {
   "title": "election_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "election_time_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} election_time_count"
    },
    {
     "expr": "election_time_sum{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} election_time_sum(ms)"
    },
    {
     "expr": "election_time_sum/election_time_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} election_avg_time(ms)"
    }
   ]
  },
  {
   "title": "quorum uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "uptime{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} uptime"
    }
   ]
  },
  {
   "title": "learner_commit_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "learner_commit_received_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} learner_commit_received_count"
    }
   ]
  },
  {
   "title": "commit_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "commit_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} commit_count"
    }
   ]
  },
  {
   "title": "snap_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "snap_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} snap_count"
    }
   ]
  },
  {
   "title": "diff_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diff_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} diff_count"
    }
   ]
  },
  {
   "title": "looking_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "looking_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} looking_count"
    }
   ]
  },
  {
   "title": "proposal_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proposal_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} proposal_count"
    }
   ]
  },
  {
   "title": "proposal_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "last_proposal_size{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} last_proposal_size"
    },
    {
     "expr": "max_proposal_size{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} max_proposal_size"
    },
    {
     "expr": "min_proposal_size{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} min_proposal_size"
    }
   ]
  },
  {
   "title": "follower_sync_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(follower_sync_time_sum{instance=~\"$instance\",job=~\"$job\"}[1m])",
     "legendFormat": "{{`{{instance}}`}} follower_sync_time"
    }
   ]
  },
  {
   "title": "learner_handler_qp_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "learner_handler_qp_size_sum{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} learner_handler_qp_size_sum sid:{{`{{key}}`}}"
    }
   ]
  },
  {
   "title": "quit_leading_due_to_disloyal_voter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quit_leading_due_to_disloyal_voter{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} quit_leading_due_to_disloyal_voter"
    }
   ]
  },
  {
   "title": "Observer Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(om_commit_process_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{`{{instance}}`}} om_commit_process_time"
    },
    {
     "expr": "rate(om_proposal_process_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{`{{instance}}`}} om_proposal_process_time"
    }
   ]
  },
  {
   "title": "Session/Watch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "watch_count{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} watch_count"
      }
     ]
    },
    {
     "title": "node_changed_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_changed_watch_count_sum{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} node_changed_watch_count"
      }
     ]
    },
    {
     "title": "node_children_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_children_watch_count_sum{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} node_children_watch_count"
      }
     ]
    },
    {
     "title": "node_deleted_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_deleted_watch_count_sum{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} node_deleted_watch_count"
      }
     ]
    },
    {
     "title": "node_created_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_created_watch_count_sum{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} node_created_watch_count"
      }
     ]
    },
    {
     "title": "revalidate_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "revalidate_count{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} revalidate_count"
      }
     ]
    },
    {
     "title": "stale_sessions_expired",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "stale_sessions_expired{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} stale_sessions_expired"
      }
     ]
    },
    {
     "title": "dead_watchers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dead_watchers_cleared{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} dead_watchers_cleared"
      },
      {
       "expr": "dead_watchers_queued{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} dead_watchers_queued"
      },
      {
       "expr": "rate(dead_watchers_cleaner_latency_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} dead_watchers_cleaner_latency"
      }
     ]
    },
    {
     "title": "add_dead_watcher_stall_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "add_dead_watcher_stall_time{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} add_dead_watcher_stall_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Client/Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "outstanding_requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "outstanding_requests{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} outstanding_requests"
      }
     ]
    },
    {
     "title": "client_response_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "last_client_response_size{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} last_client_response_size"
      },
      {
       "expr": "min_client_response_size{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} min_client_response_size"
      },
      {
       "expr": "max_client_response_size{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} max_client_response_size"
      }
     ]
    },
    {
     "title": "bytes_received_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bytes_received_count{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} bytes_received_count"
      }
     ]
    },
    {
     "title": "connection_request_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_request_count{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} connection_request_count"
      }
     ]
    },
    {
     "title": "num_alive_connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "num_alive_connections{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} num_alive_connections"
      }
     ]
    },
    {
     "title": "connection_rejected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_rejected{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} connection_rejected"
      }
     ]
    },
    {
     "title": "connection_drop_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_drop_count{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} connection_drop_count"
      }
     ]
    },
    {
     "title": "connection_drop_probability",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_drop_probability{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} connection_drop_probability"
      }
     ]
    },
    {
     "title": "sessionless_connections_expired",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sessionless_connections_expired{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} sessionless_connections_expired"
      }
     ]
    },
    {
     "title": "connection_token_deficit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(connection_token_deficit_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} connection_token_deficit"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk/Snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "open_file_descriptor",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "open_file_descriptor_count{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}}"
      }
     ]
    },
    {
     "title": "fsync_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fsynctime_sum * 1000 /fsynctime_count{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} fsynctime_avg(μs)"
      },
      {
       "expr": "irate(fsynctime_sum{instance=~\"$instance\",job=~\"$job\"}[1m])",
       "legendFormat": "{{`{{instance}}`}} fsynctime_rate"
      }
     ]
    },
    {
     "title": "snapshot_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(snapshottime_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} snapshot_time_rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Prep_Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "prep_process_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prep_process_time_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} prep_process_time"
      }
     ]
    },
    {
     "title": "prep_processor_queue_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(prep_processor_queue_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} prep_processor_queue_time_ms"
      }
     ]
    },
    {
     "title": "prep_processor_queue_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prep_processor_queue_size_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} prep_processor_queue_size"
      }
     ]
    },
    {
     "title": "prep_processor_request_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prep_processor_request_queued{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} prep_processor_request_queued"
      }
     ]
    },
    {
     "title": "outstanding_changes_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "outstanding_changes_queued{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} outstanding_changes_queued"
      },
      {
       "expr": "outstanding_changes_removed{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} outstanding_changes_removed"
      }
     ]
    },
    {
     "title": "close_session_prep_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(close_session_prep_time_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} close_session_prep_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync_Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "sync_process_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(sync_process_time_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} sync_process_time"
      }
     ]
    },
    {
     "title": "sync_processor_queue_flush_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(sync_processor_queue_flush_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} sync_processor_queue_flush_time"
      }
     ]
    },
    {
     "title": "sync_processor_queue_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(sync_processor_queue_size_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} sync_processor_queue_size"
      }
     ]
    },
    {
     "title": "sync_processor_request_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sync_processor_request_queued{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} sync_processor_request_queued"
      }
     ]
    },
    {
     "title": "sync_processor_batch_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(sync_processor_batch_size_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} sync_processor_batch_size"
      }
     ]
    }
   ]
  },
  {
   "title": "Commit_Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "commit_process_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(commit_process_time_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} commit_process_time"
      },
      {
       "expr": "rate(read_commitproc_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} read_commitproc_time"
      },
      {
       "expr": "rate(write_commitproc_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} write_commitproc_time"
      }
     ]
    },
    {
     "title": "commit_proc_req_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(write_commit_proc_req_queued_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} write_commit_proc_req_queued"
      },
      {
       "expr": "rate(read_commit_proc_req_queued_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} read_commit_proc_req_queued"
      },
      {
       "expr": "rate(commit_commit_proc_req_queued_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} commit_commit_proc_req_queued"
      }
     ]
    },
    {
     "title": "requests_in_session_queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(requests_in_session_queue_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} requests_in_session_queue"
      }
     ]
    },
    {
     "title": "commit_proc_issued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(read_commit_proc_issued_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} read_commit_proc_issued"
      },
      {
       "expr": "rate(write_commit_proc_issued_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} write_commit_proc_issued"
      }
     ]
    },
    {
     "title": "concurrent_request_processing_in_commit_processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(concurrent_request_processing_in_commit_processor_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} concurrent_request_processing_in_commit_processor"
      }
     ]
    },
    {
     "title": "time_waiting_empty_pool_in_commit_processor_read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(time_waiting_empty_pool_in_commit_processor_read_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} time_waiting_empty_pool_in_commit_processor_read"
      }
     ]
    },
    {
     "title": "pending_session_queue_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pending_session_queue_size_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} pending_session_queue_size"
      }
     ]
    },
    {
     "title": "local_write_committed_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(local_write_committed_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} local_write_committed_time_ms"
      }
     ]
    },
    {
     "title": "server_write_committed_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(server_write_committed_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} server_write_committed_time"
      }
     ]
    },
    {
     "title": "write_batch_time_in_commit_processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(write_batch_time_in_commit_processor_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} write_batch_time_in_commit_processor"
      }
     ]
    },
    {
     "title": "reads_after_write_in_session_queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(reads_after_write_in_session_queue_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} reads_after_write_in_session_queue"
      }
     ]
    },
    {
     "title": "session_queues_drained",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(session_queues_drained_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} session_queues_drained"
      }
     ]
    },
    {
     "title": "reads_issued_from_session_queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(reads_issued_from_session_queue_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} reads_issued_from_session_queue"
      }
     ]
    },
    {
     "title": "request_commit_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "request_commit_queued{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} request_commit_queued"
      }
     ]
    }
   ]
  },
  {
   "title": "Final_Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "collapsed": true,
   "panels": [
    {
     "title": "write_final_proc_time_ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(write_final_proc_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} write_final_proc_time_ms"
      }
     ]
    },
    {
     "title": "read_final_proc_time_ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(read_final_proc_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} read_final_proc_time_ms"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "read_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(readlatency_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} readlatency"
      }
     ]
    },
    {
     "title": "update_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(updatelatency_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} updatelatency"
      }
     ]
    },
    {
     "title": "max_min_avg_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max_latency{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} max_latency"
      },
      {
       "expr": "min_latency{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} min_latency"
      },
      {
       "expr": "avg_latency{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} avg_latency"
      }
     ]
    },
    {
     "title": "proposal_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(proposal_latency_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} proposal_latency"
      }
     ]
    },
    {
     "title": "quorum_ack_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(quorum_ack_latency_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} quorum_ack_latency"
      }
     ]
    },
    {
     "title": "ack_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ack_latency_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} ack_latency_sum"
      }
     ]
    },
    {
     "title": "propagation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(propagation_latency_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} propagation_latency"
      }
     ]
    },
    {
     "title": "commit_propagation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(commit_propagation_latency_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
       "legendFormat": "{{`{{instance}}`}} commit_propagation_latency"
      }
     ]
    },
    {
     "title": "proposal_ack_creation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "proposal_ack_creation_latency{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{`{{instance}}`}} proposal_ack_creation_latency-{{`{{quantile}}`}}"
      }
     ]
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "tls_handshake",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tls_handshake_exceeded{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} tls_handshake_exceeded"
    },
    {
     "expr": "outstanding_tls_handshake{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} outstanding_tls_handshake"
    }
   ]
  },
  {
   "title": "ensemble_auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ensemble_auth_fail{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} ensemble_auth_fail"
    },
    {
     "expr": "ensemble_auth_success{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} ensemble_auth_success"
    },
    {
     "expr": "ensemble_auth_skip{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} ensemble_auth_skip"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "jvm_classes_loaded",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_classes_loaded{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_current{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_deadlocked",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_deadlocked{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "jvm_pause_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_pause_time_ms_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{`{{instance}}`}} jvm_pause_time_ms"
    }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{`{{instance}}`}} gc:{{`{{gc}}`}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} state:{{`{{state}}`}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{`{{instance}}`}} pool:{{`{{pool}}`}}"
    }
   ]
  }
 ]
}